{{- if .Values.ingress.api.enabled -}}
{{- $fullName := printf "%s-api" (include "ipfs.fullname" .) -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
  {{- with .Values.ingress.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.api.host | quote }}
      secretName: {{ $fullName }}-tls
  rules:
    - host: {{ .Values.ingress.api.host | quote }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: api
{{- end -}}
