{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "ipfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  podSelector:
    matchLabels:
      {{- include "ipfs.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ipfs
  ingress:
    - from:
      - podSelector:
          matchLabels:
            {{ include "ipfs.fullname" . }}-client: "true"
      # allow communication between the pods of this chart
      - podSelector:
          matchLabels:
            {{- include "ipfs.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: ipfs
      {{- .Values.ingress.from | toYaml | nindent 6 }}
{{- end }}
