{{- $name := include "ipfs.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- include "ipfs.automaticHexSecret" (list . $name "cluster-secret" 64 .Values.cluster.secret ) }}
{{- if .Values.cluster.restApiCredentials }}
  restapi-credentials: {{ .Values.cluster.restApiCredentials | b64enc }}
{{- end }}
