apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: 5001
      protocol: TCP
      name: api
  {{- if .Values.service.api.ipAddress }}
  loadBalancerIP: {{ .Values.service.api.ipAddress | quote }}
  {{- end }}
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
