apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  ports:
    - port: 8080
      protocol: TCP
      name: http
  clusterIP: None
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
