apiVersion: v1
kind: Service
metadata:
  name: {{ include "ipfs.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ipfs.labels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
spec:
  ports:
    - port: 5001
      protocol: TCP
      name: metrics
      targetPort: api
    {{- if .Values.metrics.enabled }}
    {{- if .Values.cluster.enabled }}
    - port: 8888
      protocol: TCP
      name: cluster-metrics
      targetPort: cluster-metrics
    {{- end }}
    {{- if .Values.apiProxy.enabled }}
    - port: 6002
      protocol: TCP
      name: proxy-metrics
      targetPort: proxy-metrics
    {{- end }}
    {{- end }}
  clusterIP: None
  selector:
    {{- include "ipfs.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ipfs
