ingress:
  enabled: true
  host: "ipfs.localhost"
cluster:
  enabled: true
  consensus: raft
replicas: 3
service:
  swarm:
    - type: ClusterIP
      port: 4001
      ipAddress: null
    - type: ClusterIP
      port: 4001
      ipAddress: null
    - type: ClusterIP
      port: 4001
      ipAddress: null
global:
  dev: true
