ingress:
  enabled: true
  host: "ipfs.localhost"
cluster:
  enabled: true
  restapiCredentials: foo:supersecure
  configuration:
    cluster:
      consensus: raft
      replication_factor_min: 1
replicas: 3
service:
  swarm:
    - type: ClusterIP
      port: 4001
      ipAddress: null
    - type: ClusterIP
      port: 4001
      ipAddress: null
    - type: ClusterIP
      port: 4001
      ipAddress: null
metrics:
  enabled: true
global:
  dev: true
