ingress:
  enabled: true
  host: "ipfs.localhost"
cluster:
  enabled: true
replicas: 1
service:
  swarm:
    - type: ClusterIP
      port: 4001
      ipAddress: null
    - type: ClusterIP
      port: 4001
      ipAddress: null
